apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "6.40.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    # FIXME remove
    adminPassword: strongpassword
    sidecar:
      datasources:
        defaultDatasourceEnabled: false
        createPrometheusReplicasDatasources: false
      dashboards:
        enabled: true
        searchNamespace: ALL
        provider:
          allowUiUpdates: false
    persistence:
      type: statefulset
      enabled: false
      storageClassName: default
      accessModes:
      - ReadWriteOnce
      size: 10Gi
      finalizers:
      - kubernetes.io/pvc-protection
    podLabels:
      app: grafana
    service:
      labels:
        app: grafana
    serviceMonitor:
      enabled: true
      interval: 30s
      labels:
        tier: cluster
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          uid: prometheus_ds
          url: http://prometheus-operated.monitoring:9090
          isDefault: true
        - name: IstioPrometheus
          type: prometheus
          access: proxy
          uid: istio_prometheus_ds
          url: http://prometheus-operated.istio-system:9090
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: true
          editable: false
          options:
            path: /var/lib/grafana/dashboards/default
        - name: 'istio'
          orgId: 1
          folder: 'Istio'
          type: file
          disableDeletion: true
          editable: false
          options:
            path: /var/lib/grafana/dashboards/istio
    plugins:
    - grafana-worldmap-panel
    - grafana-clock-panel
    - grafana-piechart-panel
    - grafana-kubernetes-app
    dashboards:
      default:
      istio:
        istio-workload:
          gnetId: 7630
          revision: 68
          datasource: Prometheus
        istio-mesh:
          gnetId: 7639
          revision: 68
          datasource: Prometheus
        istio-service:
          gnetId: 7636
          revision: 68
          datasource: Prometheus
        istio-control-plane:
          gnetId: 7645
          revision: 68
          datasource: Prometheus
        istio-performance:
          gnetId: 11829
          revision: 68
          datasource: Prometheus