# Add 'helper-ui' to any changes within 'helper' folder or any subfolders
module:
  - bicep/modules/**/*

infrastructure:
  - bicep/main.js
  - bicep/private/modules/**/*

# Add 'documentation' label to any change to *.md files
documentation:
  - "*.md"
