---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m0s
  chart:
    spec:
      chart: jetstack/cert-manager
      version: 'v1.10.1'
      sourceRef:
        kind: HelmRepository
        name: jetstack
  values:
    installCRDs: true
  # install:
  #   crds: Create
  # upgrade:
  #   crds: CreateReplace