---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: ./deploy/charts/cert-manager
      sourceRef:
        kind: GitRepository
        name: cert-manager-charts
        namespace: cert-manager
  install:
    crds: Create
  interval: 10m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
