---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: jetstack/cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: 'v1.10.1'
  install:
    crds: Create
  interval: 10m0s
  releaseName: cert-manager
  targetNamespace: kube-system
  upgrade:
    crds: CreateReplace