---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
      version: 'v1.10.1'
  install:
    crds: Create
  interval: 10m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  upgrade:
    crds: CreateReplace