---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-profile
spec:
  profile: default
  hub: "docker.io/istio"
  tag: "1.15.1"
  values:
    telemetry:
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              disable_host_header_fallback: true
            outboundSidecar:
              disable_host_header_fallback: true
            gateway:
              disable_host_header_fallback: true
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    enableTracing: false
    defaultConfig:
      holdApplicationUntilProxyStarts: true
  components:
    pilot:
      enabled: true
    cni:
      enabled: false
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
    egressGateways:
    - name: istio-egressgateway
      enabled: false
