---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
    toolkit.fluxcd.io/tenant: app
  name: app

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    istio-injection: enabled
    toolkit.fluxcd.io/tenant: app
  name: app
  namespace: app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    istio-injection: enabled
    toolkit.fluxcd.io/tenant: app
  name: app-reconciler
  namespace: app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:app:reconciler
- kind: ServiceAccount
  name: app
  namespace: app
