---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: app
  namespace: app
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: app
  url: https://github.com/danielscholl/gitops-osdu-app-core
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app
  namespace: app
spec:
  interval: 5m0s
  path: ./
  prune: true
  serviceAccountName: app
  sourceRef:
    kind: GitRepository
    name: app
