apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: applications
  namespace: flux-system
spec:
  dependsOn:
    - name: software
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./applications/stamp
  prune: true
  validation: client