apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-version
  namespace: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
data:
  version: 1.13.3
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./software/istio/system
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: osdu-bicep
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: istio-version